# Generated by Django 4.1.4 on 2023-02-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="festivalartist",
            options={"ordering": ["date"]},
        ),
        migrations.AlterUniqueTogether(
            name="festivalartist",
            unique_together={("festival", "artist", "date")},
        ),
    ]
